import { EnumVideoPlayerQuality } from '@/video/dto/video.types'

export const ZARAK_VIDEOS = [
	{
		title:
			'FED UP',
		viewsCount: 20063,
		thumbnailUrl: '/uploads/thumbnails/fedup.avif',
		slug: 'FED-UP7K_0NRLCu4',
		videoFileName: 'fedup.mp4',
		maxResolution: EnumVideoPlayerQuality['2K'],
		description:
			'<p>Provided to YouTube by DistroKid</p><p>FED UP · Baker Ya Maker · Baker Ya Maker</p><p>FED UP</p><p>℗ Evilspeak Records</p><p>Released on: 2026-07-24</p><p>Auto-generated by YouTube.</p>',
		channelSlug: 'zarak',
		isPublic: true,
		tags: [
			'FedUp',
			'BakerYaMaker',
		],
		createdAt: '2026-07-23T14:30:00Z'
	},
	{
		title: 'Decisions of Torment',
		viewsCount: 4229619,
		thumbnailUrl: '/uploads/thumbnails/decisions.avif',
		slug: 'decisionsh33594a6af3f',
		videoFileName: 'decisions.mp4',
		maxResolution: EnumVideoPlayerQuality['1080p'],
		description:
			'<p>Provided to YouTube by DistroKid</p><p>Decisions of Torment · Devilish Trio</p><p>The Collection</p><p>℗ 722461 Records DK</p><p>Released on: 2017-10-07</p><p>Auto-generated by YouTube.</p>',
		channelSlug: 'zarak',
		isPublic: true,
		tags: [
			'trio',
			'DevilishTrio'
		],
		createdAt: '2017-11-15T14:30:00Z'
	},
]
