import { EnumVideoPlayerQuality } from '@/video/dto/video.types'
import { STORAGE_URL } from 'scripts/storage'

export const ZHABKA_VIDEOS = [
  {
    title: '2hollis - poster boy (Slowed Reverb) (Best part) (Versión Tik Tok) Chico lachowski',
    viewsCount: 8984521,
    thumbnailUrl: `${STORAGE_URL}/thumbnails/posteyboy.avif`,
    slug: 'posteyboy7K_0NRLCu4',
    videoFileName: 'posteyboy.mp4',
    maxResolution: EnumVideoPlayerQuality['480p'],
    description:
      '<p>just be confident ⚡🔥</p><p>original Audio: <a href="https://www.youtube.com/watch?v=H2vTrHc-OGk" target="_blank">2hollis - poster boy (official audio)</a></p><p>video author: 3mirlgg</p>',
    channelSlug: 'zhabka',
    isPublic: true,
    tags: [
      'PosterBoy',
      '2hollis',
    ],
		createdAt: '2023-05-11T14:30:00Z'
  },
  {
    title: 'NEON PULSE',
    viewsCount: 77683,
    thumbnailUrl: `${STORAGE_URL}/thumbnails/neon.avif`,
    slug: 'neonh33594a6af3f',
    videoFileName: 'neon.mp4',
    maxResolution: EnumVideoPlayerQuality['1080p'],
    description:
      '<p>Provided to YouTube by Echo8</p><p>NEON PULSE · ZANETHRO</p><p>NEON PULSE</p><p>℗ Echo8</p><p>Released on: 2024-12-01</p><p>Composer: Bryson Lee Taylor</p><p>Lyricist: Bryson Lee Taylor</p><p>Auto-generated by YouTube.</p>',
    channelSlug: 'zhabka',
    isPublic: true,
    tags: [
      'NeonPulse',
      'Zanethro'
    ],
		createdAt: '2025-03-25T14:30:00Z'
  },
]
